### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by Kev0123** [angelnu/ioBroker.chromecast#15]
Hi,
I cant get your adapter to work with a clean raspi setup
`

chromecast.0 | 2017-10-12 18:03:08.218 | info | cleaned everything up...
-- | -- | -- | --
chromecast.0 | 2017-10-12 18:03:08.217 | error | at process._tickCallback (internal/process/next_tick.js:104:9)
chromecast.0 | 2017-10-12 18:03:08.217 | error | at _combinedTickCallback (internal/process/next_tick.js:77:11)
chromecast.0 | 2017-10-12 18:03:08.217 | error | at listOnTimeoutNT (timers.js:276:26)
chromecast.0 | 2017-10-12 18:03:08.217 | error | at Timer.listOnTimeout (timers.js:214:5)
chromecast.0 | 2017-10-12 18:03:08.217 | error | at tryOnTimeout (timers.js:250:5)
chromecast.0 | 2017-10-12 18:03:08.217 | error | at ontimeout (timers.js:386:11)
chromecast.0 | 2017-10-12 18:03:08.217 | error | at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3083:38)
chromecast.0 | 2017-10-12 18:03:08.217 | error | at Adapter.emit (events.js:191:7)
chromecast.0 | 2017-10-12 18:03:08.217 | error | at emitTwo (events.js:111:20)
chromecast.0 | 2017-10-12 18:03:08.217 | error | at ChromecastDevice._ioBrokerChange (/opt/iobroker/node_modules/iobroker.chromecast/lib/chromecastDevice.js:756:15)
chromecast.0 | 2017-10-12 18:03:08.217 | error | TypeError: Cannot read property 'from' of null
chromecast.0 | 2017-10-12 18:03:08.216 | error | uncaught exception: Cannot read property 'from' of null
chromecast.0 | 2017-10-12 18:03:08.147 | info | cleaned everything up...
chromecast.0 | 2017-10-12 18:03:08.146 | error | at process._tickCallback (internal/process/next_tick.js:104:9)
chromecast.0 | 2017-10-12 18:03:08.146 | error | at _combinedTickCallback (internal/process/next_tick.js:77:11)
chromecast.0 | 2017-10-12 18:03:08.146 | error | at listOnTimeoutNT (timers.js:276:26)
chromecast.0 | 2017-10-12 18:03:08.146 | error | at Timer.listOnTimeout (timers.js:214:5)
chromecast.0 | 2017-10-12 18:03:08.146 | error | at tryOnTimeout (timers.js:250:5)
chromecast.0 | 2017-10-12 18:03:08.146 | error | at ontimeout (timers.js:386:11)
chromecast.0 | 2017-10-12 18:03:08.146 | error | at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3083:38)
chromecast.0 | 2017-10-12 18:03:08.146 | error | at Adapter.emit (events.js:191:7)
chromecast.0 | 2017-10-12 18:03:08.146 | error | at emitTwo (events.js:111:20)
chromecast.0 | 2017-10-12 18:03:08.146 | error | at ChromecastDevice._ioBrokerChange (/opt/iobroker/node_modules/iobroker.chromecast/lib/chromecastDevice.js:756:15)
chromecast.0 | 2017-10-12 18:03:08.146 | error | TypeError: Cannot read property 'from' of null
chromecast.0 | 2017-10-12 18:03:08.146 | error | uncaught exception: Cannot read property 'from' of null
chromecast.0 | 2017-10-12 18:03:08.137 | info | cleaned everything up...
chromecast.0 | 2017-10-12 18:03:08.135 | error | at Timer.listOnTimeout (timers.js:214:5)
chromecast.0 | 2017-10-12 18:03:08.135 | error | at tryOnTimeout (timers.js:250:5)
chromecast.0 | 2017-10-12 18:03:08.135 | error | at ontimeout (timers.js:386:11)
chromecast.0 | 2017-10-12 18:03:08.135 | error | at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3083:38)
chromecast.0 | 2017-10-12 18:03:08.135 | error | at Adapter.emit (events.js:191:7)
chromecast.0 | 2017-10-12 18:03:08.135 | error | at emitTwo (events.js:111:20)
chromecast.0 | 2017-10-12 18:03:08.135 | error | at ChromecastDevice._ioBrokerChange (/opt/iobroker/node_modules/iobroker.chromecast/lib/chromecastDevice.js:756:15)
chromecast.0 | 2017-10-12 18:03:08.135 | error | TypeError: Cannot read property 'from' of null
chromecast.0 | 2017-10-12 18:03:08.134 | error | uncaught exception: Cannot read property 'from' of null
chromecast.0 | 2017-10-12 18:03:06.780 | info | starting. Version 1.3.0 in /opt/iobroker/node_modules/iobroker.chromecast, node: v6.11.4
chromecast.0 | 2017-10-12 18:03:06.724 | info | States connected to redis: 0.0.0.0:6379
host.ioBroker | 2017-10-12 18:03:05.120 | info | instance system.adapter.chromecast.0 started with pid 1045
host.ioBroker | 2017-10-12 18:02:35.092 | info | Restart adapter system.adapter.chromecast.0 because enabled
host.ioBroker | 2017-10-12 18:02:35.091 | error | instance system.adapter.chromecast.0 terminated with code 0 (OK)
chromecast.0 | 2017-10-12 18:02:34.501 | info | cleaned everything up...
chromecast.0 | 2017-10-12 18:02:34.500 | error | at process._tickCallback (internal/process/next_tick.js:104:9)
chromecast.0 | 2017-10-12 18:02:34.500 | error | at _combinedTickCallback (internal/process/next_tick.js:77:11)
chromecast.0 | 2017-10-12 18:02:34.500 | error | at listOnTimeoutNT (timers.js:276:26)
chromecast.0 | 2017-10-12 18:02:34.500 | error | at Timer.listOnTimeout (timers.js:214:5)
chromecast.0 | 2017-10-12 18:02:34.500 | error | at tryOnTimeout (timers.js:250:5)
chromecast.0 | 2017-10-12 18:02:34.500 | error | at ontimeout (timers.js:386:11)
chromecast.0 | 2017-10-12 18:02:34.500 | error | at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3083:38)
chromecast.0 | 2017-10-12 18:02:34.500 | error | at Adapter.emit (events.js:191:7)
chromecast.0 | 2017-10-12 18:02:34.500 | error | at emitTwo (events.js:111:20)
chromecast.0 | 2017-10-12 18:02:34.500 | error | at ChromecastDevice._ioBrokerChange (/opt/iobroker/node_modules/iobroker.chromecast/lib/chromecastDevice.js:756:15)
chromecast.0 | 2017-10-12 18:02:34.500 | error | TypeError: Cannot read property 'from' of null
chromecast.0 | 2017-10-12 18:02:34.499 | error | uncaught exception: Cannot read property 'from' of null
chromecast.0 | 2017-10-12 18:02:34.485 | info | cleaned everything up...
chromecast.0 | 2017-10-12 18:02:34.482 | error | at Timer.listOnTimeout (timers.js:214:5)
chromecast.0 | 2017-10-12 18:02:34.482 | error | at tryOnTimeout (timers.js:250:5)
chromecast.0 | 2017-10-12 18:02:34.482 | error | at ontimeout (timers.js:386:11)
chromecast.0 | 2017-10-12 18:02:34.482 | error | at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3083:38)
chromecast.0 | 2017-10-12 18:02:34.482 | error | at Adapter.emit (events.js:191:7)
chromecast.0 | 2017-10-12 18:02:34.482 | error | at emitTwo (events.js:111:20)
chromecast.0 | 2017-10-12 18:02:34.482 | error | at ChromecastDevice._ioBrokerChange (/opt/iobroker/node_modules/iobroker.chromecast/lib/chromecastDevice.js:756:15)
chromecast.0 | 2017-10-12 18:02:34.482 | error | TypeError: Cannot read property 'from' of null
chromecast.0 | 2017-10-12 18:02:34.480 | error | uncaught exception: Cannot read property 'from' of null
chromecast.0 | 2017-10-12 18:02:33.290 | info | starting. Version 1.3.0 in /opt/iobroker/node_modules/iobroker.chromecast, node: v6.11.4
chromecast.0 | 2017-10-12 18:02:33.228 | info | States connected to redis: 0.0.0.0:6379
host.ioBroker | 2017-10-12 18:02:31.633 | info | instance system.adapter.chromecast.0 started with pid 989
host.ioBroker | 2017-10-12 18:02:01.610 | info | Restart adapter system.adapter.chromecast.0 because enabled
host.ioBroker | 2017-10-12 18:02:01.609 | error | instance system.adapter.chromecast.0 terminated with code 0 (OK)
chromecast.0 | 2017-10-12 18:02:01.152 | info | cleaned everything up...
chromecast.0 | 2017-10-12 18:02:01.151 | error | at process._tickCallback (internal/process/next_tick.js:104:9)
chromecast.0 | 2017-10-12 18:02:01.151 | error | at _combinedTickCallback (internal/process/next_tick.js:77:11)
chromecast.0 | 2017-10-12 18:02:01.151 | error | at listOnTimeoutNT (timers.js:276:26)
chromecast.0 | 2017-10-12 18:02:01.151 | error | at Timer.listOnTimeout (timers.js:214:5)
chromecast.0 | 2017-10-12 18:02:01.151 | error | at tryOnTimeout (timers.js:250:5)
chromecast.0 | 2017-10-12 18:02:01.151 | error | at ontimeout (timers.js:386:11)
chromecast.0 | 2017-10-12 18:02:01.151 | error | at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3083:38)
chromecast.0 | 2017-10-12 18:02:01.151 | error | at Adapter.emit (events.js:191:7)
chromecast.0 | 2017-10-12 18:02:01.151 | error | at emitTwo (events.js:111:20)
chromecast.0 | 2017-10-12 18:02:01.151 | error | at ChromecastDevice._ioBrokerChange (/opt/iobroker/node_modules/iobroker.chromecast/lib/chromecastDevice.js:756:15)
chromecast.0 | 2017-10-12 18:02:01.151 | error | TypeError: Cannot read property 'from' of null
chromecast.0 | 2017-10-12 18:02:01.150 | error | uncaught exception: Cannot read property 'from' of null
chromecast.0 | 2017-10-12 18:02:01.141 | info | cleaned everything up...
chromecast.0 | 2017-10-12 18:02:01.139 | error | at Timer.listOnTimeout (timers.js:214:5)
chromecast.0 | 2017-10-12 18:02:01.139 | error | at tryOnTimeout (timers.js:250:5)
chromecast.0 | 2017-10-12 18:02:01.139 | error | at ontimeout (timers.js:386:11)
chromecast.0 | 2017-10-12 18:02:01.139 | error | at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3083:38)
chromecast.0 | 2017-10-12 18:02:01.139 | error | at Adapter.emit (events.js:191:7)
chromecast.0 | 2017-10-12 18:02:01.139 | error | at emitTwo (events.js:111:20)
chromecast.0 | 2017-10-12 18:02:01.139 | error | at ChromecastDevice._ioBrokerChange (/opt/iobroker/node_modules/iobroker.chromecast/lib/chromecastDevice.js:756:15)
chromecast.0 | 2017-10-12 18:02:01.139 | error | TypeError: Cannot read property 'from' of null
chromecast.0 | 2017-10-12 18:02:01.137 | error | uncaught exception: Cannot read property 'from' of null
chromecast.0 | 2017-10-12 18:01:59.912 | info | starting. Version 1.3.0 in /opt/iobroker/node_modules/iobroker.chromecast, node: v6.11.4
chromecast.0 | 2017-10-12 18:01:59.850 | info | States connected to redis: 0.0.0.0:6379

`

**Comment by christofkac** [comment]
Hi,
I suffer from the same problem - is there at least a work around to get the adapter up and running?
Bye
Christof

**Comment by Kev0123** [comment]
I got it fixed via an update of ioBroker via ssh. The update in GUI wont do anything, the one triggered over ssh fixed my issues.

**Comment by Apollon77** [comment]
1.3.2 fixes the problem, but only available on Github and not on npm :-(

@angelnu Please update officially to 1.3.2 including stable repo!

**Comment by angelnu** [comment]
I released 1.3.3 to npm - I will update the stable repo next

**Comment by angelnu** [comment]
Released 1.3.4 and provided a PR to update the stable repo: https://github.com/ioBroker/ioBroker.repositories/pull/73
