### ISSUE TITLE
Can't set temporary volume for announcements

### ISSUE THREAD

**Issue by Juweii** [angelnu/ioBroker.chromecast#19]
Hello!

I tried to add an announcement as a door bell - the current streaming should pause and the door bell should be announced. After that, the streaming should continue.

To archieve that i used the state "announcement":
`setState("chromecast.0.MyRoom.player.announcement", '{"url":"http://192.168.xxxx.xxxx/mp3/Ding-dong-chime.mp3","volume":60}');`

But only the json element "url" will be used, "volume" is ignored.

Is there any way to send the announcement using defined volume and don't change the volume in general?
Changing the volume using `chromecast.0.MyRoom.status.volume` is very unhandy, because the music stream is too loud with that volume...

Or any way to use castv2-player directly to archieve this?

Thank you in advanced,
Juergen

**Comment by angelnu** [comment]
Uhm, this should work: it is exactly what the sayit adapter does.

Could you please indicate what version of the adapter are you using and attach a log?

**Comment by Juweii** [comment]
Hello angelnu,

theres no informative log:
```
chromecast.0 | 2018-01-03 14:12:45.853 | info | MyChromcast - Finished playing announcement
-- | -- | -- | --
chromecast.0 | 2018-01-03 14:12:43.390 | info | MyChromcast - Playing - http://192.168.xxx.xxx/mp3/Ding-dong-chime.mp3
chromecast.0 | 2018-01-03 14:12:40.335 | info | MyChromcast - Playing playlist with 1 item
```

Iobroker javascript call:
```
    setState("chromecast.0.MyChromcast.player.announcement", '{"url":"http://192.168.xxx.xxx/mp3/Ding-dong-chime.mp3","volume":60}');
```

The volume is as it was defined by device and is not getting changed.
Makes no difference if i change it to even `"volume":100` or `"volume":10`.

Using 1.3.5 of https://github.com/angelnu/ioBroker.chromecast

Best regards,
Juergen

**Comment by angelnu** [comment]
Please set the log level for the Chromecast adapter to `debug`.

**Comment by Juweii** [comment]
That's not more informations...
```
chromecast.0	2018-01-04 16:06:47.994	info	MyChromecast - Finished playing announcement
chromecast.0	2018-01-04 16:06:44.778	info	MyChromecast - Playing - http://192.168.xxx.xxx/mp3/Ding-dong-chime.mp3
javascript.0	2018-01-04 16:06:43.055	info	Stop script script.js.common.Skript1
chromecast.0	2018-01-04 16:06:42.484	info	MyChromecast - Playing playlist with 1 items
chromecast.0	2018-01-04 16:06:41.580	info	MyChromecast - Try to play playlist with 1 items
chromecast.0	2018-01-04 16:06:41.471	info	MyChromecast - Try to play url - http://192.168.xxx.xxx/mp3/Ding-dong-chime.mp3
chromecast.0	2018-01-04 16:06:41.468	info	MyChromecast - Player joint
chromecast.0	2018-01-04 16:06:41.466	info	MyChromecast - Connected player
chromecast.0	2018-01-04 16:06:41.465	info	MyChromecast - Default player lauched
chromecast.0	2018-01-04 16:06:41.463	info	MyChromecast - Connected player
chromecast.0	2018-01-04 16:06:41.454	info	MyChromecast - Try to join player
chromecast.0	2018-01-04 16:06:41.419	info	MyChromecast - Try to launch default player
chromecast.0	2018-01-04 16:06:41.415	debug	MyChromecast - device stateChange chromecast.0.MyChromecast.player.announcement {'val':'{\'url\':\'http://192.168.xxx.xxx/mp3/Ding-dong-chime.mp3\',\'volume\':10}','ack':false,'ts':1515078401408,'q':0,'from':'system.adapter.javascript.0','lc':1514997338012}
javascript.0	2018-01-04 16:06:41.403	info	script.js.common.Skript1: registered 0 subscriptions and 0 schedules
javascript.0	2018-01-04 16:06:41.204	info	Start javascript script.js.common.Skript1
```

**Comment by angelnu** [comment]
I think I know what it is happening: the volume is only used when you play an announcement while another playlist is being played. When the Chromecast is idle at the time of the announcement another code path is followed that ignores the volume.

Could you please confirm my theory and test the announcement while something else is being played? Thanks.

**Comment by Juweii** [comment]
Hello angelnu,
hmm, i made some tests. If the announcement occurs, it stops the current stream and is playing the mp3 sound. Even volume:10 plays it in the previous volume. After the announcement the previous stream isn't started again as is stay in "Default media receiver" with playing: true even after the mp3 has been finished.

Strange, as i read from yous posts that shouldn't look like that..?!

**Comment by angelnu** [comment]
These are the logs I get when I try an announcement with sayit while playing a radio stream:

```
chromecast.0
2018-01-08 01:07:25.278
info
audio-playroom - queueRemove
chromecast.0
2018-01-08 01:07:25.268
info
audio-playroom - Playing - http://klassikradio.hoerradar.de/klassikradio-live-mp3-hq?sABC=5n52o5sp%230%2394ro277q50838s57717882rr299qnops%23fgernz.xynffvxenqvb.qr&amsparams=playerid:stream.klassikradio.de;skey:1515369980
chromecast.0
2018-01-08 01:07:25.268
info
audio-playroom - Back to regular playlist
chromecast.0
2018-01-08 01:07:20.765
info
audio-playroom - getStatus
chromecast.0
2018-01-08 01:07:20.758
info
audio-playroom - queueRemove
chromecast.0
2018-01-08 01:07:20.745
info
audio-playroom - Playing - http://192.168.2.200:30082/state/sayit.0.tts.mp3
chromecast.0
2018-01-08 01:07:20.745
info
audio-playroom - Resumed after announcement
chromecast.0
2018-01-08 01:07:16.993
info
audio-playroom - setting volume to same value 70 - ignored
chromecast.0
2018-01-08 01:07:16.252
info
audio-playroom - getStatus
chromecast.0
2018-01-08 01:07:16.245
info
audio-playroom - queueRemove
chromecast.0
2018-01-08 01:07:16.235
info
audio-playroom - Back to regular playlist
chromecast.0
2018-01-08 01:07:16.234
info
audio-playroom - Playing - http://192.168.2.200:30082/state/sayit.0.tts.mp3
chromecast.0
2018-01-08 01:07:16.233
info
audio-playroom - Resumed after announcement
chromecast.0
2018-01-08 01:07:13.290
info
audio-playroom - setting volume to same value 70 - ignored
chromecast.0
2018-01-08 01:07:13.220
info
audio-playroom - set volume to 70
chromecast.0
2018-01-08 01:07:13.207
info
audio-playroom - getStatus
chromecast.0
2018-01-08 01:07:12.913
info
audio-playroom - setting volume to same value 13 - ignored
chromecast.0
2018-01-08 01:07:12.506
info
audio-playroom - set volume to 13
chromecast.0
2018-01-08 01:07:12.405
info
audio-playroom - queueInsert
chromecast.0
2018-01-08 01:07:12.383
info
audio-playroom - getStatus
chromecast.0
2018-01-08 01:07:12.372
info
audio-playroom - queueInsert
chromecast.0
2018-01-08 01:07:12.348
info
audio-playroom - Try to play announcement - 'http://192.168.2.200:30082/state/sayit.0.tts.mp3'
sayit.0
2018-01-08 01:07:12.335
error
null
sayit.0
2018-01-08 01:07:12.334
info
Copied file '/opt/iobroker/node_modules/iobroker.sayit/lib/../say.mp3' to '/opt/iobroker/cache/0ef7b0bfb33a011bb6fba8678ea14431.mp3'
sayit.0
2018-01-08 01:07:12.314
info
Set 'chromecast.0.audio-playroom.player.announcement to {'url':'http://192.168.2.200:30082/state/sayit.0.tts.mp3','volume':70}```

How does yours look like when playing an announcement while playing music?

I will fix the volume not being recognised when the device is iddle but it will likelly take me  couple of weeks since I will be traveling.

**Comment by Juweii** [comment]
Did you try changing the announcement object using some mp3 file? Within sayit adapter I think the volume works, will test that at evening.

**Comment by Juweii** [comment]
I also face the problem when playing music (spotify for example), the announcement is getting played and after that the music will not proceed to play. It just stops / hanging in the default media player.
Hmmm...

**Comment by angelnu** [comment]
The adapter is currently only able to resume playing if music/radio was being played with the default player. Spotify has its own player so without reverse engineering it it is not possible to resume playing.

I wonder if in this case the volume is recognised even if the music does not resume.

Anyway I still have to fix the situation where the player is not playing during the announcement...
