### ISSUE TITLE
Adjustment in io.package.json invalid causing iobroker beeing unable to retrieve adapters from repros

### ISSUE THREAD

**Issue by DutchmanNL** [angelnu/ioBroker.chromecast#23]
please undo : https://github.com/angelnu/ioBroker.chromecast/commit/6fc8336a0555ff5d5b45e9cf985c75e1cb33e7a1#diff-e977eea076d776fb0e8218602ac1e57c

This commit (adding objects within title) causes iobroker beeing unable to retrieve his repository list. #22 

fix provided in pull request #24

**Comment by angelnu** [comment]
@DutchmanNL @GermanBluefox : should I then close this?

**Comment by DutchmanNL** [comment]
Yes please
