### ISSUE TITLE
Youtube URL in url2play does not work to play on chromecast

### ISSUE THREAD

**Issue by ramizh** [angelnu/ioBroker.chromecast#31]
Trying to play a YouTube video on chromecast through the adapter for some testing, and it seems that it doesnt work. Did I misunderstood something or should Chromecast play the content of the url iI input in that field?

Log:

chromecast.0 | 2018-02-24 21:21:23.103 | error | Chromecast - Cannot play file "https://www.youtube.com/watch?v=G2P_jFN0Pr8": Error: queueLoad failed
-- | -- | -- | --
chromecast.0 | 2018-02-24 21:21:23.095 | error | at Client.emit (events.js:201:7)
chromecast.0 | 2018-02-24 21:21:23.095 | error | at emitMany (events.js:132:20)
chromecast.0 | 2018-02-24 21:21:23.095 | error | at Client.onmessage (/opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2/lib/channel.js:23:10)
chromecast.0 | 2018-02-24 21:21:23.095 | error | at Channel.emit (events.js:191:7)
chromecast.0 | 2018-02-24 21:21:23.095 | error | at emitTwo (events.js:106:13)
chromecast.0 | 2018-02-24 21:21:23.095 | error | at Channel.onmessage  (/opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-client/lib/controllers/controller.js:16:10)
chromecast.0 | 2018-02-24 21:21:23.095 | error | at MediaController.emit (events.js:191:7)
chromecast.0 | 2018-02-24 21:21:23.095 | error | at emitTwo (events.js:111:20)
chromecast.0 | 2018-02-24 21:21:23.095 | error | at MediaController.onmessage  (/opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-client/lib/controllers/request-response.js:27:7)
chromecast.0 | 2018-02-24 21:21:23.095 | error | at /opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-client/lib/controllers/media.js:149:23
chromecast.0 | 2018-02-24 21:21:23.095 | error | Chromecast - Error playing playlist - Error: queueLoad failed
chromecast.0 | 2018-02-24 21:21:21.620 | info | Chromecast - Try to play playlist with 1 items
chromecast.0 | 2018-02-24 21:21:21.617 | info | Chromecast - Player joint
chromecast.0 | 2018-02-24 21:21:21.615 | info | Chromecast - Connected player
chromecast.0 | 2018-02-24 21:21:21.614 | info | Chromecast - Default player lauched
chromecast.0 | 2018-02-24 21:21:21.612 | info | Chromecast - Connected player
chromecast.0 | 2018-02-24 21:21:21.601 | info | Chromecast - Try to join player
chromecast.0 | 2018-02-24 21:21:20.384 | info | Chromecast - Detached player
chromecast.0 | 2018-02-24 21:21:20.280 | info | Chromecast - Player joint
chromecast.0 | 2018-02-24 21:21:20.278 | info | Chromecast - Connected player
chromecast.0 | 2018-02-24 21:21:20.271 | warn | Chromecast - Reconnected -> continue
chromecast.0 | 2018-02-24 21:21:20.266 | info | Chromecast - Try to join player
chromecast.0 | 2018-02-24 21:21:20.215 | info | Chromecast - Connected client
chromecast.0 | 2018-02-24 21:21:19.054 | warn | Chromecast - Waiting up to 10 seconds for connection to chromecast
chromecast.0 | 2018-02-24 21:21:19.050 | info | Chromecast - Try to launch default player
chromecast.0 | 2018-02-24 21:21:18.983 | info | Chromecast - Try to play url - https://www.youtube.com/watch?v=G2P_jFN0Pr8

**Comment by angelnu** [comment]
This adapter can only play audio/video streams that do not require an special application. YouTube has its own application so people cannot copy the videos and therefore cannot be used with this adapter.

You can try `http://commondatastorage.googleapis.com/gtv-videos-bucket/CastVideos/dash/BigBuckBunnyAudio.mp4`
