### ISSUE TITLE
AndroidTV recognized at Chromecast causing warn-logs

### ISSUE THREAD

**Issue by Haileid** [angelnu/ioBroker.chromecast#33]
I didn't know how to most precisley describe this. I got a Sony Android TV with built in Chromecast and the adapter seems to be unable to connect to and keeps throwing errors. Multiple per second.
Is there any possibility I can exclude this device from the list?
ALso got a "normal" Chromecast which I don't want to loose in ioBroker by uninatalling the adaptor.

Here's an excerpt from the log:
`chromecast.0 | 2018-03-28 23:15:30.797 | warn | Wohnzimmer - Client error: Error: read ECONNRESET at exports._errnoException (util.js:1020:11) at TLSWrap.onread (net.js:580:26)
-- | -- | -- | --
chromecast.0 | 2018-03-28 23:15:26.781 | warn | Wohnzimmer - Client error: Error: read ECONNRESET at exports._errnoException (util.js:1020:11) at TLSWrap.onread (net.js:580:26)
chromecast.0 | 2018-03-28 23:15:23.766 | warn | Wohnzimmer - Client error: Error: socket hang up at TLSSocket.onHangUp (_tls_wrap.js:1124:19) at TLSSocket.g (events.js:292:16) at emitNone (events.js:91:20) at TLSSocket.emit (events.
chromecast.0 | 2018-03-28 23:15:21.753 | warn | Wohnzimmer - Client error: Error: read ECONNRESET at exports._errnoException (util.js:1020:11) at TLSWrap.onread (net.js:580:26)
chromecast.0 | 2018-03-28 23:15:20.737 | warn | Wohnzimmer - Client error: Error: read ECONNRESET at exports._errnoException (util.js:1020:11) at TLSWrap.onread (net.js:580:26)
chromecast.0 | 2018-03-28 23:15:20.695 | info | Wohnzimmer - client disconnected
chromecast.0 | 2018-03-28 23:15:20.443 | info | Wohnzimmer - Connected client
chromecast.0 | 2018-03-28 23:15:20.374 | info | Wohnzimmer - client disconnected
chromecast.0 | 2018-03-28 23:15:19.522 | info | Wohnzimmer - Connected client
chromecast.0 | 2018-03-28 23:15:19.497 | warn | Wohnzimmer - Client error: Error: socket hang up at TLSSocket.onHangUp (_tls_wrap.js:1124:19) at TLSSocket.g (events.js:292:16) at emitNone (events.js:91:20) at TLSSocket.emit (events.
chromecast.0 | 2018-03-28 23:15:19.445 | info | Wohnzimmer - client disconnected
chromecast.0 | 2018-03-28 23:15:18.906 | info | Wohnzimmer - Connected client
chromecast.0 | 2018-03-28 23:15:18.879 | warn | Wohnzimmer - Client error: Error: read ECONNRESET at exports._errnoException (util.js:1020:11) at TLSWrap.onread (net.js:580:26)
chromecast.0 | 2018-03-28 23:15:17.921 | warn | Wohnzimmer - Client error: Error: socket hang up at TLSSocket.onHangUp (_tls_wrap.js:1124:19) at TLSSocket.g (events.js:292:16) at emitNone (events.js:91:20) at TLSSocket.emit (events.
chromecast.0 | 2018-03-28 23:15:16.910 | warn | Wohnzimmer - Client error: Error: socket hang up at TLSSocket.onHangUp (_tls_wrap.js:1124:19) at TLSSocket.g (events.js:292:16) at emitNone (events.js:91:20) at TLSSocket.emit (events.
chromecast.0 | 2018-03-28 23:15:16.904 | info | Wohnzimmer - client disconnected
chromecast.0 | 2018-03-28 23:15:16.902 | warn | Wohnzimmer - Client error: Error: socket hang up at TLSSocket.onHangUp (_tls_wrap.js:1124:19) at TLSSocket.g (events.js:292:16) at emitNone (events.js:91:20) at TLSSocket.emit (events.
chromecast.0 | 2018-03-28 23:15:15.970 | info | Wohnzimmer - Connected client
chromecast.0 | 2018-03-28 23:15:15.878 | warn | Wohnzimmer - Client error: Error: read ECONNRESET at exports._errnoException (util.js:1020:11) at TLSWrap.onread (net.js:580:26)
chromecast.0 | 2018-03-28 23:15:15.770 | info | Wohnzimmer - client disconnected
chromecast.0 | 2018-03-28 23:15:14.920 | info | Wohnzimmer - Connected client
chromecast.0 | 2018-03-28 23:15:14.881 | warn | Wohnzimmer - Client error: Error: socket hang up at TLSSocket.onHangUp (_tls_wrap.js:1124:19) at TLSSocket.g (events.js:292:16) at emitNone (events.js:91:20) at TLSSocket.emit (events.
chromecast.0 | 2018-03-28 23:15:13.947 | warn | Wohnzimmer - Client error: Error: read ECONNRESET at exports._errnoException (util.js:1020:11) at TLSWrap.onread (net.js:580:26)
chromecast.0 | 2018-03-28 23:15:13.918 | info | Wohnzimmer - client disconnected
chromecast.0 | 2018-03-28 23:15:13.677 | info | Wohnzimmer - Connected client
chromecast.0 | 2018-03-28 23:15:11.667 | warn | Wohnzimmer - Client error: Error: socket hang up at TLSSocket.onHangUp (_tls_wrap.js:1124:19) at TLSSocket.g (events.js:292:16) at emitNone (events.js:91:20) at TLSSocket.emit (events.
chromecast.0 | 2018-03-28 23:15:07.654 | warn | Wohnzimmer - Client error: Error: read ECONNRESET at exports._errnoException (util.js:1020:11) at TLSWrap.onread (net.js:580:26)
chromecast.0 | 2018-03-28 23:15:04.637 | warn | Wohnzimmer - Client error: Error: socket hang up at TLSSocket.onHangUp (_tls_wrap.js:1124:19) at TLSSocket.g (events.js:292:16) at emitNone (events.js:91:20) at TLSSocket.emit (events.`

**Comment by angelnu** [comment]
I can add a "disabled" state to each Chromecast so that if it is set to true the adaptor does not try to connect.

Until I find a few minutes to code and test it you might want to disable the adapter logs as circumvention.

**Comment by Haileid** [comment]
That would be absolutely great.


Vegetto <notifications@github.com> schrieb am Do., 29. März 2018, 06:18:

**Comment by angelnu** [comment]
@Haileid - please try version 1.4.3. It is only in git -> I will push to npm after hearing from you.

In your case you need to set `Wohnzimmer.enabled` to false

**Comment by Haileid** [comment]
Thanks for your effort. Will try and report back. I also played around
yesterday and figured out ths real problem. I had a TV and Google home with
the same name interferrring. After giving unique names the initial problem
also seems to be solved.



Vegetto <notifications@github.com> schrieb am Di., 3. Apr. 2018, 02:26:
