### ISSUE TITLE
2.1.5 Sayit Adapter don't work with Google Mini

### ISSUE THREAD

**Issue by Brainbug01** [angelnu/ioBroker.chromecast#44]
I installed Version 2.1.5 and then my 3 Sayit Adapter don't work with the Google Mini. Version 2.0.5 all Google Mini speak speak the text with script's. And now no Google Mini will Talk to me?

**Comment by angelnu** [comment]
So this was a regression with 2.1.5 since you indicate that it worked before with 2.0.5?

If this is the case could you please try with the latest 2.2.0 version in github? If the issue is still there could you please append the log?

**Comment by Brainbug01** [comment]
2.2.0 works with my 3 Google Mini, thanks.
