### ISSUE TITLE
No Auto-Detection in Docker

### ISSUE THREAD

**Issue by petterpet** [angelnu/ioBroker.chromecast#47]
I'm using Docker. ioBroker doesn't find any Cast-Devices.
Which Port should I expose?
Or can I add a device manually?

**Comment by angelnu** [comment]
Discovery relays in the MDNS protocol which does not pass through routers such as the one used by docker. There are three options:
- run the iobroker with net=host
- use a MDNS proxy (https://hub.docker.com/r/angelnu/mdns_repeater)  <- I use this (see my kubernetes recipe for the two required env variables)
- (new in version 2.2) manually add the chromecast device in the addapter settings in iobroker

**Comment by petterpet** [comment]
Thanks!
I added my devices manually. 

Is port 8009 correct? Should I expose it in my container?
And what is the ip-address of an audio group?

**Comment by angelnu** [comment]
The port for audio groups is dynamic. I am not sure if it stays the same for the group after creation of if it changes also afterwards. I use autodetection to avoid worries about this.

The IP address for the group is the IP from one of the group members.

You do not need to open any port in the iobroker container for this adapter to connect to the Google home devices.

**Comment by petterpet** [comment]
I'm not able to controll my groups anymore, so the port must have changed.
I will verify this on the weekend with my test-ioBroker on an Raspberry Pi and tell the result.
