### ISSUE TITLE
Error "Cannot read property 'volume' of undefined"

### ISSUE THREAD

**Issue by misanorot** [angelnu/ioBroker.chromecast#50]
> Caught | 2019-02-07 21:17:46.408 | error | by controller[1]: at /opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-client/lib/controllers/receiver.js:31:5
> -- | -- | -- | --
> Caught | 2019-02-07 21:17:46.408 | error | by controller[1]: at /opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-player/lib/persistentClient.js:251:20
> Caught | 2019-02-07 21:17:46.408 | error | by controller[1]: at PersistentClient._updateStatus (/opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-player/lib/persistentClient.js:323:12)
> Caught | 2019-02-07 21:17:46.408 | error | by controller[1]: at PersistentClient.emit (events.js:214:7)
> Caught | 2019-02-07 21:17:46.408 | error | by controller[1]: at emitTwo (events.js:131:20)
> Caught | 2019-02-07 21:17:46.408 | error | by controller[1]: at MediaPlayer.emit (events.js:214:7)
> Caught | 2019-02-07 21:17:46.408 | error | by controller[1]: at emitTwo (events.js:126:13)
> Caught | 2019-02-07 21:17:46.408 | error | by controller[1]: at ChromecastDevice._updateClientStatus (/opt/iobroker/node_modules/iobroker.chromecast/lib/chromecastDevice.js:610:80)
> Caught | 2019-02-07 21:17:46.408 | error | by controller[1]: at MediaPlayer.getVolume (/opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-player/lib/mediaPlayer.js:76:27)
> Caught | 2019-02-07 21:17:46.408 | error | by controller[1]: at PersistentClient.getVolume (/opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-player/lib/persistentClient.js:150:45)
> Caught | 2019-02-07 21:17:46.408 | error | by controller[1]: TypeError: Cannot read property 'volume' of undefined
> Caught | 2019-02-07 21:17:46.408 | error | by controller[0]: at /opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-client/lib/controllers/receiver.js:31:5
> Caught | 2019-02-07 21:17:46.408 | error | by controller[0]: at /opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-player/lib/persistentClient.js:251:20
> Caught | 2019-02-07 21:17:46.408 | error | by controller[0]: at PersistentClient._updateStatus (/opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-player/lib/persistentClient.js:323:12)
> Caught | 2019-02-07 21:17:46.408 | error | by controller[0]: at PersistentClient.emit (events.js:214:7)
> Caught | 2019-02-07 21:17:46.408 | error | by controller[0]: at emitTwo (events.js:131:20)
> Caught | 2019-02-07 21:17:46.408 | error | by controller[0]: at MediaPlayer.emit (events.js:214:7)
> Caught | 2019-02-07 21:17:46.408 | error | by controller[0]: at emitTwo (events.js:126:13)
> Caught | 2019-02-07 21:17:46.408 | error | by controller[0]: at ChromecastDevice._updateClientStatus (/opt/iobroker/node_modules/iobroker.chromecast/lib/chromecastDevice.js:610:80)
> Caught | 2019-02-07 21:17:46.408 | error | by controller[0]: at MediaPlayer.getVolume (/opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-player/lib/mediaPlayer.js:76:27)
> Caught | 2019-02-07 21:17:46.408 | error | by controller[0]: at PersistentClient.getVolume (/opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-player/lib/persistentClient.js:150:45)
> Caught | 2019-02-07 21:17:46.408 | error | by controller[0]: TypeError: Cannot read property 'volume' of undefined
> Caught | 2019-02-07 21:17:46.408 | error | by controller[0]: at /opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-client/lib/controllers/receiver.js:31:5
> Caught | 2019-02-07 21:17:46.408 | error | by controller[0]: at /opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-player/lib/persistentClient.js:251:20
> Caught | 2019-02-07 21:17:46.408 | error | by controller[0]: at PersistentClient._updateStatus (/opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-player/lib/persistentClient.js:323:12)
> Caught | 2019-02-07 21:17:46.408 | error | by controller[0]: at PersistentClient.emit (events.js:214:7)
> Caught | 2019-02-07 21:17:46.408 | error | by controller[0]: at emitTwo (events.js:131:20)
> Caught | 2019-02-07 21:17:46.408 | error | by controller[0]: at MediaPlayer.emit (events.js:214:7)
> Caught | 2019-02-07 21:17:46.408 | error | by controller[0]: at emitTwo (events.js:126:13)
> Caught | 2019-02-07 21:17:46.408 | error | by controller[0]: at ChromecastDevice._updateClientStatus (/opt/iobroker/node_modules/iobroker.chromecast/lib/chromecastDevice.js:610:80)
> Caught | 2019-02-07 21:17:46.408 | error | by controller[0]: at MediaPlayer.getVolume (/opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-player/lib/mediaPlayer.js:76:27)
> Caught | 2019-02-07 21:17:46.408 | error | by controller[0]: at PersistentClient.getVolume (/opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-player/lib/persistentClient.js:150:45)
> Caught | 2019-02-07 21:17:46.408 | error | by controller[0]: TypeError: Cannot read property 'volume' of undefined
> Caught | 2019-02-07 21:17:46.408 | error | by controller[0]: at /opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-client/lib/controllers/receiver.js:31:5
> Caught | 2019-02-07 21:17:46.408 | error | by controller[0]: at /opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-player/lib/persistentClient.js:251:20
> Caught | 2019-02-07 21:17:46.408 | error | by controller[0]: at PersistentClient._updateStatus (/opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-player/lib/persistentClient.js:323:12)
> Caught | 2019-02-07 21:17:46.408 | error | by controller[0]: at PersistentClient.emit (events.js:214:7)
> Caught | 2019-02-07 21:17:46.408 | error | by controller[0]: at emitTwo (events.js:131:20)
> Caught | 2019-02-07 21:17:46.408 | error | by controller[0]: at MediaPlayer.emit (events.js:214:7)
> Caught | 2019-02-07 21:17:46.407 | error | by controller[0]: at emitTwo (events.js:126:13)
> Caught | 2019-02-07 21:17:46.407 | error | by controller[0]: at ChromecastDevice._updateClientStatus (/opt/iobroker/node_modules/iobroker.chromecast/lib/chromecastDevice.js:610:80)
> Caught | 2019-02-07 21:17:46.407 | error | by controller[0]: at MediaPlayer.getVolume (/opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-player/lib/mediaPlayer.js:76:27)
> Caught | 2019-02-07 21:17:46.407 | error | by controller[0]: at PersistentClient.getVolume (/opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-player/lib/persistentClient.js:150:45)
> Caught | 2019-02-07 21:17:46.407 | error | by controller[0]: TypeError: Cannot read property 'volume' of undefined

**Comment by angelnu** [comment]
Adding some additional checks to prevent the exception is simple but I would like to know what caused it. Usually the reason is that the connection to the device closed unexpected. Could you please confirm if this is the case?

A full log of the Chromecast adapter would really help to understand the context when the error happened.

**Comment by misanorot** [comment]
Hey,
no problem but the debug log has a lot of private informations. Have you an email adress for me?

And the issue is directly after the start.... very short green flag and than red.

**Comment by angelnu** [comment]
It was a race condition - fixed in the cast-player library. I will release a new version with a bunch of fixes.

**Comment by misanorot** [comment]
Thanks

**Comment by angelnu** [comment]
Fixed in v2.2.3
