### ISSUE TITLE
Update in stable repository

### ISSUE THREAD

**Issue by Apollon77** [angelnu/ioBroker.chromecast#61]
table is still on 2.0.0 ... here 2.2.3

**Comment by angelnu** [comment]
@Apollon77 - what is the process to update the version in the stable table?

**Comment by Apollon77** [comment]
see https://github.com/ioBroker/ioBroker.repositories#update-of-the-version-in-stable :-)

**Comment by angelnu** [comment]
Open https://github.com/ioBroker/ioBroker.repositories/pull/472

**Comment by Apollon77** [comment]
thank you
